hathitrust/otis

- .rubocop.yml
- Gemfile
- Gemfile.lock
- README.md
- app/controllers/ht_users_controller.rb
- app/models/ht_user.rb
- app/views/ht_users/edit.html.erb
- app/views/ht_users/index.html.erb
- app/views/ht_users/show.html.erb
- app/views/shared/_flash_message.html.erb
- config/routes.rb
- db/keycard.yml
- db/schema.rb
- test/application_system_test_case.rb
- test/controllers/ht_users_controller_test.rb
- test/controllers/users_controller_test.rb
- test/fixtures/ht_users.yml
- test/fixtures/users.yml
- test/models/ht_user_test.rb
- test/models/user_test.rb
- test/test_helper.rb
Add edit page and a whole lot of plumbing so that we have actual tests.
> Addresses HT-1196 update static IP

- .travis.yml
- Gemfile
- Gemfile.lock
- db/keycard.yml
- test/models/ht_user_test.rb
Had to disable the keycard gem which was causing no end of problems.
> Addresses HT-1492 continuous integration

- .rubocop.yml
- app/controllers/ht_users_controller.rb
- app/models/ht_institution.rb
- app/models/ht_user.rb
- app/views/ht_users/index.html.erb
- app/views/ht_users/show.html.erb
- db/schema.rb
- db/seeds.rb
- test/controllers/ht_users_controller_test.rb
- test/fixtures/ht_institutions.yml
- test/fixtures/ht_users.yml
Part of the ticket relates to grouping by institution for batch operations. Since sorting by columns is not implemented yet, I'm taking that as not part of the MVP for the current effort.
> Addresses HT-1455 display institution name.

- app/controllers/application_controller.rb
- app/controllers/fake_shib_controller.rb
- app/controllers/session_controller.rb
- app/views/shared/_header.html.erb
- app/views/shared/login_form.html.erb
- config/routes.rb
- config/settings.yml
- config/settings/development.yml
- test/controllers/session_controller_test.rb
Not sure about where the Shib settings should live, or how they need to be tweaked further.
The second commit has also been deployed on Staging.
> HT-1529 integrate shib

- README.md
- app/assets/stylesheets/application.css.sass
- app/assets/stylesheets/users.scss
- app/controllers/ht_users_controller.rb
- app/models/ht_user.rb
- app/views/ht_users/edit.html.erb
- app/views/ht_users/show.html.erb
- test/controllers/ht_users_controller_test.rb
Update user edit page to include approver contact field along
with minor style updates to show/edit pages.
> HT-1204 allow update of approver contact

- app/views/shared/_header.html.erb
Pulled this out of the approval request branch since it will be useful to wire some other branches into this (e.g., UI for ht_institutions I am also working on).
> Bootstrap 3 adjustments and nav menu in header.

- app/controllers/application_controller.rb
- app/controllers/approval_controller.rb
- app/models/ht_approval_request.rb
- test/controllers/approval_controller_test.rb
- test/test_helper.rb
- render not found page if token is nonsense
- allow unknown user to use the one-time use token
> HT-1585: Fixes for one-time use token

- config/application.rb
- config/settings/development.yml
I verified this change works in production (i.e. the setting gets picked up and email gets through)
> HT-2369: email setting for production

- app/controllers/ht_institutions_controller.rb
- app/models/ht_institution.rb
- app/views/ht_institutions/index.html.erb
- app/views/ht_institutions/show.html.erb
- app/views/shared/_header.html.erb
- config/routes.rb
- db/schema.rb
- db/seeds.rb
- test/controllers/ht_institutions_controller_test.rb
- test/factories.rb
- test/models/ht_institution_test.rb
Merging is a low priority. That said, this should not require any more work for now. There's no creation or editing capability.
> HT-2349 Add ht_institutions display.

- app/mailers/application_mailer.rb
- config/settings.yml
- test/mailers/approval_request_mailer_test.rb
- test/mailers/user_mailer_test.rb
- from is picked up from config
- also bccs that address by default
> HT-2117, HT-1195: bcc configurable address

- app/controllers/ht_approval_requests_controller.rb
- app/controllers/ht_users_controller.rb
- app/helpers/application_helper.rb
- app/models/ht_approval_request.rb
- app/models/ht_user.rb
- app/presenters/ht_user_presenter.rb
- app/views/ht_approval_requests/index.html.erb
- app/views/ht_users/index.html.erb
- app/views/ht_users/show.html.erb
- test/controllers/ht_approval_requests_controller_test.rb
- test/factories.rb
- test/models/ht_approval_request_test.rb
- test/models/ht_user_test.rb
This comes out of some review Melissa and I did on the workflow and missing pieces before starting the renewal next week. Going to merge it so we can get it in production but please give it a look when you have a chance next week.
> Punch list items for renewal requests

- app/presenters/ht_approval_request_presenter.rb
- app/views/ht_approval_requests/index.html.erb
- config/locales/en.yml
Also taking the opportunity to do some l11n on badge text.
Should the presenter code be further structured into a {label, class, i11n key} data structure and unpacked?
> Addresses HT-2476 Make 'expired' label say 'request expired'

- app/models/ht_institution.rb
- app/presenters/ht_institution_presenter.rb
- app/views/ht_institutions/index.html.erb
- app/views/ht_institutions/show.html.erb
- config/locales/en.yml
- db/schema.rb
- db/seeds.rb
- test/factories.rb
- test/models/ht_institution_test.rb
- test/presenters/ht_institution_presenter_test.rb
- Modify `schema.rb` and `HTInstitution` to honor `tinyint` as integer
- Add `HTInstitutionPresenter` with badging
This branch is currently deployed on `useradmin-staging`
> HT-2511 ht_institutions.enabled is not Boolean

- app/controllers/ht_users_controller.rb
- test/controllers/ht_users_controller_test.rb
This works but is a little bit messy. @billdueber do you by any chance have a more idiomatic way of doing this?
> HT-2535: Ensure setting mfa=1 unsets IP restriction

- app/views/ht_users/index.html.erb
Change the two buttons under active users list to type `submit` so they work again.
> Fix ht_users index page submit buttons.

- app/mailers/application_mailer.rb
- config/settings.yml
- test/mailers/approval_request_mailer_test.rb
- test/mailers/user_mailer_test.rb
I've already set this in the production config, so it should get picked up as soon as we deploy this.
> HT-2413: Set Reply-To from configuration

- app/mailers/approval_request_mailer.rb
- app/mailers/registration_mailer.rb
- app/mailers/user_mailer.rb
- app/views/approval_request_mailer/approval_request_email.html.erb
- app/views/registration_mailer/registration_email.html.erb
- app/views/user_mailer/approval_request_user_email.html.erb
- test/controllers/ht_approval_requests_controller_test.rb
- test/controllers/ht_registrations_controller_test.rb
- test/mailers/approval_request_mailer_test.rb
- test/mailers/registration_mailer_test.rb
- test/mailers/user_mailer_test.rb
- Add official HathiTrust horizontal logo to registration and approval request e-mails.
> DEV-61 E-mail Branding

- app/views/shared/_registration_body.html.erb
- New language for registration e-mail vetted by Melissa S.
> DEV-261 Include ATRS instruction link in OTIS registration e-mail

- app/models/ht_user.rb
- test/lib/tasks/daily_digest_test.rb
- test/models/ht_user_test.rb
- Add test for expiring_soon scope.
- Use five-day window in daily digest test to avoid Ruby/SQL date squishiness.
> DEV-54 daily digest fix for overbroad "expiring soon" list.

- app/presenters/ht_registration_presenter.rb
- config/locales/en.yml
- config/locales/ja.yml
- config/settings.yml
- db/seeds.rb
- test/presenters/ht_registration_presenter_test.rb
- Should look at this with MS in a test environment.
> DEV-218 Authentication data matching for registration

- .github/workflows/tests.yaml
- README.md
- app/controllers/ht_approval_requests_controller.rb
- app/controllers/ht_registrations_controller.rb
- app/views/ht_registrations/index.html.erb
- app/views/shared/_header.html.erb
- bin/run_system_tests.sh
- config/initializers/assets.rb
- config/settings/test.yml
- docker-compose.yml
- lib/tasks/clear_database.rake
- test/application_system_test_case.rb
- test/system/ht_approval_requests_test.rb
- test/system/ht_registrations_test.rb
- test/system/ht_users_test.rb
- test/test_helper.rb
Initial go at using ActionDispatch::SystemTestCase for system/feature testing
- Registration workflow.
- Approval request workflow.
- Use Capybara/Selenium with Docker. No luck with Cuprite.
> DEV-354 Feature Specs

- .dockerignore
- .github/workflows/build-main.yaml
- .github/workflows/manual-deploy-testing.yaml
- .github/workflows/tag-release.yaml
- .github/workflows/tests.yaml
- Gemfile
- Gemfile.lock
- README.md
- test/test_helper.rb
- Use shared actions from github.com/hathitrust/github_actions
- Use coveralls
> Update github actions workflows

- config/locales/en.yml
- config/locales/ja.yml
- db/schema.rb
- db/seeds.rb
Remove ht_institutions.emergency_conteact field which is no longer present in our actual databases.
> Remove ht_institutions.emergency_conteact from schema

- .github/dependabot.yml
From https://github.com/mlibrary/search.account/blob/main/.github/dependabot.yml
> Add dependabot multi-ecosystem updates
