hathitrust/otis

.travis.yml
Gemfile
Gemfile.lock
README.md
app/controllers/session_controller.rb
config.ru
config/application.rb
config/database.yml
config/settings.yml
config/settings/development.yml
config/settings/test.yml
db/schema.rb
db/seeds.rb

This sets up relative url root handling that works in dev.
It does not work in test with a relative url root of anything other than '/' (among other things it complains there are no matching routes) for reasons I don't care to debug at the moment.
This also sets up default dev & test database config so that it can be used locally out of the box without requiring a mysql setup.

HT-1506: Configure relative url root

---

app/controllers/ht_users_controller.rb
app/models/ht_user.rb
app/views/ht_users/edit.html.erb
app/views/ht_users/index.html.erb
test/fixtures/ht_users.yml
test/models/ht_user_test.rb
test/test_helper.rb

Branch name is a lie, it's a button that pulls in the current timestamp as the user's expiration date.

Addresses HT-1198 update user as expired.

---

.rubocop.yml
app/models/ht_user.rb
db/seeds.rb
test/controllers/ht_users_controller_test.rb
test/factories.rb
test/models/ht_user_test.rb

Main change is the iprestrict validation being turned off if mfa is true. Changes to DB seeds and test factory to create mfa = true records.
Minor change to iprestrict= method to allow setting to nil, not sure if that is something that would happen in a production environment but I needed it (apparently) for the ht_user_mfa factory.

Addresses HT-2007 iprestrict should be allowed to be NULL if MFA = true

---

.rubocop.yml
app/models/expiration_date.rb
app/models/ht_user.rb
app/views/ht_users/edit.html.erb
app/views/ht_users/index.html.erb
app/views/ht_users/show.html.erb
bin/bundle
test/factories.rb
test/models/expiration_date_test.rb
test/models/ht_user_test.rb

(This touches a *lot* of files, but only `app/models/expiration_date.rb` 
and the associated test file should need more than a cursory review)
The expiration date is being manipulated enough that
it's worth breaking out into its own class that
can compute things (e.g., whether it's expired,
how long until it expires, etc.)
An expiration date is both the actual 
date and the expires type (e.g, "expiresannually"). Expiration dates are
*compared* only by date.
Expiration dates are always dates only; the
time is thrown away. A quick question to Melissa
verified that this is ok.
https://hathitrust.slack.com/archives/DKV93G37T/p1576770049002400
The HTUser object now creates a new expiration date
object on creation and whenever `expires` is set and
forwards appropriate methods to it. The …

Build an actual object for the expiration_date

---

app/views/ht_users/show.html.erb
test/controllers/ht_users_controller_test.rb

Fix -- and fixed test -- for a nil iprestrict crashing HTUsers show page due to non-use of safe nav operator (and/or iprestrict returning nil instead of empty array but that's an issue for another day).

Fix HTUser show page crash on nil iprestrict.

---

app/controllers/approval_controller.rb
app/controllers/ht_approval_requests_controller.rb
app/controllers/ht_users_controller.rb
app/models/ht_approval_request.rb
app/presenters/ht_approval_request_presenter.rb
app/presenters/ht_user_presenter.rb
app/views/ht_approval_requests/edit.html.erb
app/views/ht_approval_requests/index.html.erb
app/views/ht_approval_requests/show.html.erb
app/views/ht_users/edit.html.erb
app/views/ht_users/index.html.erb
app/views/ht_users/show.html.erb
app/views/shared/_approval_request_email.html.erb
app/views/shared/approval.html.erb
config/application.rb
config/settings/development.yml
db/schema.rb
db/seeds.rb
test/controllers/approval_controller_test.rb
test/controllers/ht_approval_requests_controller_test.rb
test/models/ht_approval_request_test.rb
test/presenters/ht_approval_request_presenter_test.rb
test/presenters/ht_user_presenter_test.rb

Highlights:
- Walks back renewing users immediately on receipt of approval, in favor of adding a new field `renewed` to record the additional step of HathiTrust staff renewing manually or as a batch (to be implemented on a separate ticket).
- Badges galore!
- `ht_approval_request` show and edit page are no longer clones of each other. The latter is now the one with the e-mail preview. There's probably lots of fun stuff that can be done with the show page, right now it is pretty sparse.
- `db/seeds.rb` tries to generate some more interesting/realistic approval requests.
- Expired renewal requests can be resent.
- There's some nascent support for separating out the renewed requests as if they were no longer active.

HT-1472 user approval status visible.

---

app/controllers/session_controller.rb
app/models/ht_approval_request.rb

We need to come back from shib and hit /login so that the session gets
properly populated.

Redirect back to /login instead of eventual target page

---

app/controllers/approval_controller.rb
app/controllers/ht_approval_requests_controller.rb
app/mailers/approval_request_mailer.rb
app/models/ht_approval_request.rb
app/views/approval_request_mailer/approval_request_email.text.erb
app/views/shared/_approval_request_email.html.erb
config/application.rb
config/environments/development.rb
config/environments/test.rb
db/schema.rb
test/controllers/ht_approval_requests_controller_test.rb
test/factories.rb
test/mailers/approval_request_mailer_test.rb
test/models/ht_approval_request_test.rb

See notes on individual commits.
I've verified on useradmin-testing that I can:
- generate an approval request
- send the email
- receive the email
- use the link in the email when logged in as a non-privileged user (after changing the url to development)

HT-1585: fixes for one-time links

---

app/controllers/ht_approval_requests_controller.rb
app/controllers/ht_users_controller.rb
app/helpers/application_helper.rb
app/models/ht_user.rb
app/presenters/ht_user_presenter.rb
app/views/ht_approval_requests/index.html.erb
app/views/ht_users/edit.html.erb
app/views/ht_users/index.html.erb
test/controllers/approval_controller_test.rb
test/controllers/ht_approval_requests_controller_test.rb
test/controllers/ht_users_controller_test.rb
test/models/ht_user_test.rb

As demonstrated to HT staff 2020-05-21.
Issue with excessively sticky flash message fixed.
Issue with existing approval request not being updated from approver -> HT staff not addressed because we don't know the extent of out-of-band communication with the approver, so for now let's leave the approver's identity intact on the request, even if (in the unlikely event) the request e-mail was never sent.

HT-2115 and HT-1940 renewal for multiple users.

---

.rubocop.yml
app/controllers/ht_approval_requests_controller.rb
app/mailers/user_mailer.rb
app/views/shared/_approval_request_user_email.html.erb
app/views/user_mailer/approval_request_user_email.html.erb
app/views/user_mailer/approval_request_user_email.text.erb
test/mailers/previews/approval_request_mailer_preview.rb
test/mailers/previews/user_mailer_preview.rb
test/mailers/user_mailer_test.rb

Left open the option of previewing the HTML e-mail in the approval request edit page, but that would require instantiating HTUser in the view, or some other cleverness.
A couple of additional commits with routine fixes thrown in.

Ht 2351 approval user email

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/controllers/ht_approval_requests_controller.rb
app/mailers/approval_request_mailer.rb
app/views/approval_request_mailer/approval_request_email.html.erb
app/views/approval_request_mailer/approval_request_email.text.erb
app/views/ht_approval_requests/edit.html.erb
app/views/ht_approval_requests/show.html.erb
app/views/shared/_approval_request_body.html.erb
app/views/shared/_approval_request_user_table.html.erb
config/initializers/assets.rb
config/initializers/ckeditor.rb
test/controllers/ht_approval_requests_controller_test.rb
test/mailers/approval_request_mailer_test.rb

- Adds ckeditor for HTML editing
- Does not (yet) persist the email anywhere after it's sent
- Disable turbolinks, since it messes with ckeditor

HT-1195: make email to approvers editable

---

app/controllers/session_controller.rb
config/settings.yml
config/settings/development.yml
config/settings/test.yml

This allows us to specify a URL for the WAYF to send users through
rather than defaulting to a specific IdP, which is necessary for the
one-time use links and not a problem for manager user.

HT-2397: simplify shib config

---

app/controllers/application_controller.rb
app/lib/otis/authentication/user_pid.rb
app/models/user.rb
test/models/user_test.rb

This fixes an issue where users' authentication is rejected whose
identity provider do not send eduPersonPrincipalName or another
attribute that can be mapped to user_eid.
Otis::Authentication::UserPid is a straight copy-paste of
Keycard::Authentication::UserEid and included here without tests. It
should be tested when it is integrated into Keycard.
I will test this with useradmin-testing by removing Apache sending eduPersonPrincipalName, mail, etc headers and ensuring that authentication still succeeds.

HTS-139075: accept user_pid attribute for authentication

---

app/models/ht_user.rb
app/models/ip_restriction.rb
db/seeds.rb
test/controllers/ht_users_controller_test.rb
test/factories.rb
test/models/ht_user_test.rb
test/models/ip_restriction_test.rb

This fixes an issue where users whose iprestriction was set to `^.*$` could not be edited. For now this displays as "any" for the IP restriction.

HT-2408: Add ability to remove IP restriction

---

app/helpers/application_helper.rb
app/views/shared/_header.html.erb
test/controllers/approval_controller_test.rb
test/controllers/ht_users_controller_test.rb

Construct the nav structure at a higher level than before and suppress the Home link and Go menu when the structure is empty.

HT-2468 one-time use links should not show menu links that are unauthorized

---

app/controllers/ht_institutions_controller.rb
app/models/ht_institution.rb
app/presenters/ht_institution_presenter.rb
app/views/ht_institutions/_form.html.erb
db/schema.rb
db/seeds.rb
test/controllers/ht_institutions_controller_test.rb
test/factories.rb
test/models/ht_billing_member_test.rb
test/models/ht_institution_test.rb
test/presenters/ht_institution_presenter_test.rb

- Remove `ht_institutions` fields that are no longer present in production
- Improve behavior for billing members. The `accepts_attributes_for` stuff is kind of a mess, esp. in figuring out whether or not to add/edit something; longer term, it would probably be better to explicitly just add a form for that object rather than having it as nested attributes. I thought `accepts_attributes_for` would be easier since it's a 1:1 relationship, but in fact it creates a bit of a mess. I think if we want to make more changes to billing members it's probably worth experimenting with other options here.

db schema updates; billing member fixes

---

Dockerfile
Dockerfile.prod

Not sure about changing the `CMD` in `Dockerfile` as opposed to `Dockerfile.prod` -- I believe it to be unused. Changing it to parallel the production file anyway.

Run assets:precompile at runtime after RAILS_RELATIVE_URL_ROOT is set

---

config/environments/production.rb
kube/environments/staging/main.jsonnet
kube/environments/testing/main.jsonnet
kube/lib/otis/config.libsonnet
kube/lib/otis/otis.libsonnet

Rails 5 defaulted to debug logging in production, but this is noisy, can leak PII, and not allowed by A&E policy.
This changes the default level to info but allows overriding it via `RAILS_LOG_LEVEL`, then sets it back to debug for testing & staging.
FYI @botimer

use RAILS_LOG_LEVEL; log at INFO level by default in production

---

app/models/ht_user.rb
test/models/ht_user_test.rb

Applies only to manually-expired users, when the approval request has not been sent or responded to by approver.
Works in the same way as manual change of approver, by deleting stale approval requests.

HT-2452 do not re-request approval for expired users.

---

app/controllers/ht_contacts_controller.rb
app/views/ht_contacts/index.html.erb
test/controllers/ht_contacts_controller_test.rb

- Contacts index page can restrict to type via a dropdown menu.
- Add download CSV button.

HT-3129 view and download contacts by type

---

app/controllers/ht_approval_requests_controller.rb
app/models/ht_approval_request.rb
app/presenters/ht_approval_request_presenter.rb
app/views/ht_approval_requests/index.html.erb
app/views/ht_contact_types/show.html.erb
app/views/ht_contacts/show.html.erb
test/controllers/ht_approval_requests_controller_test.rb
test/controllers/ht_contacts_controller_test.rb

Also change "delete" buttons for contacts and contact types to a "danger" style for consistency with the purge button added to the approval requests index.
There's also a fix for one of the HTInstitution tests that wasn't HTML-escaping the institution name. There are likely others. (Culprit was an unescaped apostrophe.)

HT-3159 purge request expired labels

---

Gemfile
Gemfile.lock
app/views/layouts/application.html.erb

- Replace deprecated sass-rails with sassc-rails.
- Bump bootstrap-table version to address table border anomaly.

HT-3225 fix warning about SASS

---

app/controllers/application_controller.rb
app/lib/otis/authorization/resource.rb
app/models/application_record.rb
app/models/ht_approval_request.rb
app/models/ht_contact.rb
app/models/ht_contact_type.rb
app/models/ht_institution.rb
app/models/ht_user.rb
app/policies/application_policy.rb
app/policies/ht_approval_requests_policy.rb
app/views/ht_users/index.html.erb
lib/tasks/migrate_users.rake
test/policies/application_policy_test.rb
test/policies/ht_approval_requests_policy_test.rb

- Add Checkpoint policies derived from controller or resource type (more meta stuff than I would have liked, perhaps).
- Address pluralization mismatch between our grants (`lib/tasks/migrate_users.rake`) and model `#resource_type`.
-  I don't really like the `#resource_type` pluralization route but this preserves the grants we have in production.
- We still don't do any per-object auth checks (i.e., can I edit myself), but we should now be able to if needed.

HT-3054 users with admin ht_users can't admin approval requests

---

app/models/ht_approval_request.rb
app/models/ht_contact.rb
app/models/ht_contact_type.rb
app/models/ht_log.rb
app/models/ht_registration.rb
db/schema.rb

This doesn't rename any of the classes in the application, just the
database tables themselves.
Eventually, I think it would make sense to put everything under an `Otis` namespace, e.g.
```ruby
module Otis
class Registration
...
end
end
```
That requires bigger changes and will almost certainly cause merge conflicts with any other work in progress, so we should probably discuss and coordinate that a bit more when/if we want to do that.

HT-3224: Rename database tables

---

app/controllers/application_controller.rb
app/views/ht_approval_requests/index.html.erb
app/views/ht_contact_types/index.html.erb
app/views/ht_contact_types/show.html.erb
app/views/ht_contacts/index.html.erb
app/views/ht_contacts/show.html.erb
app/views/ht_institutions/index.html.erb
app/views/ht_institutions/show.html.erb
app/views/ht_registrations/show.html.erb
app/views/ht_users/index.html.erb
app/views/ht_users/show.html.erb
bin/grants

As far as I can tell, we should now singularize the resource types for
grants, and we can use the class names when calling 'can?'.
There are a number of places wehere we could clean things up by removing
some logic from views and potentially simplifying that logic through
policies, but but changing that is out of the scope of this commit.

Singularize resources for grants

---

app/models/ht_institution.rb
app/models/ht_user.rb
app/presenters/ht_institution_presenter.rb
app/views/ht_users/edit.html.erb
app/views/ht_users/show.html.erb
db/schema.rb
db/seeds.rb
test/controllers/ht_users_controller_test.rb
test/models/ht_user_test.rb

- Add a new column `ht_users.inst_id` while deprecating `ht_users.identity_provider`.
- Do not enforce validity of `inst_id` when creating users since it breaks a number of tests. Right now the UI doesn't allow editing, and registrations restrict selection to menu of institutions, so I'm not too concerned about that right now.
- **This will require a production schema change before rollout.**
- CRMS uses the field in a routine that appears not to be called currently but this needs to be investigated a bit more deeply.
- Check in with Roger and Bill for possible issues with MDP lib/tools or whatever might lurk.

HT-3304 ht_users should join on inst_id, not entityID

---

Gemfile
Gemfile.lock
app/controllers/finalize_controller.rb
app/controllers/ht_registrations_controller.rb
app/models/ht_registration.rb
app/views/ht_registrations/preview.html.erb
app/views/shared/finalize.html.erb
test/controllers/finalize_controller_test.rb
test/controllers/ht_registrations_controller_test.rb

- Further patterned after what we do with approval requests.
- Not sure about the wording for different MFA/non-MFA scenarios. Expect some cleanup with HT-1212.
- Some new logic for SEND/RESEND link in the e-mail preview.

HT-3156 landing page to confirm user registrations

---

app/controllers/finalize_controller.rb
app/controllers/ht_registrations_controller.rb
app/lib/otis/registration_mover.rb
app/models/ht_registration.rb
app/models/ht_user.rb
app/presenters/ht_registration_presenter.rb
app/presenters/ht_user_presenter.rb
app/views/ht_registrations/index.html.erb
app/views/ht_registrations/show.html.erb
config/initializers/services.rb
config/locales/en.yml
config/locales/ja.yml
config/routes.rb
db/schema.rb
db/seeds.rb
test/controllers/finalize_controller_test.rb
test/controllers/ht_registrations_controller_test.rb
test/presenters/ht_registration_presenter_test.rb
test/presenters/ht_user_presenter_test.rb
test/test_helper.rb

- Add app/lib/otis/registration_mover.rb for stuffing registration data into new user.
- Add ability to edit ht_user usertype, role, access for newly-registered users.
- Display WHOIS data on registration show page for received registrations (we have the IP address).

HT-1194 HathiTrust staff member can finalize registration in ht_users

---

app/presenters/ht_contact_presenter.rb
app/presenters/ht_registration_presenter.rb
app/views/layouts/application.html.erb

- Use Select2 (select2.org) which appears to be the JS used by HT WAYF.
- Also use Select2 locale files for each of our available locales.
- This facility is currently used only for institution select menus used with registrations and contacts.

HT-3360 Keyboard-aware institution pop-up menu

---

app/controllers/ht_approval_requests_controller.rb
app/controllers/ht_registrations_controller.rb
app/mailers/approval_request_mailer.rb
app/mailers/registration_mailer.rb
app/views/ht_approval_requests/edit.html.erb
app/views/ht_registrations/preview.html.erb
app/views/layouts/application.html.erb
config/locales/en.yml
config/locales/ja.yml
test/controllers/ht_approval_requests_controller_test.rb
test/controllers/ht_registrations_controller_test.rb

- Approval request UI updated for feature parity.
- ckeditor UI language synchronized with OTIS locale.
- Borked-up 'de' locale setting for ckeditor (left over from big localization experiment) fixed.
- Use `I18n.locale` instead of `params[:locale]`.

HT-3362 Registration e-mail subject line should be editable

---

app/models/ht_institution.rb

Some institutions use the employee affiliation; it is worthwhile to be consistent and generous in terms of what we can accept to reduce support issues later.

Add employee affiliation by default

---

app/views/ht_registrations/show.html.erb
test/controllers/ht_registrations_controller_test.rb

- Sent registrations can be deleted just like unsent ones.
- Once received or finished the option to delete disappears (another strategy must be used for auto-hiding or removing old data).
- Use `assert_select` in tests as it is more reliable than string matching with path helpers.

DEV-49 allow deletion of sent registration

---

app/assets/stylesheets/otis.scss
app/controllers/finalize_controller.rb
app/views/finalize/edit.html.erb
app/views/finalize/show.html.erb
config/locales/en.yml
config/locales/ja.yml
db/seeds.rb
test/controllers/finalize_controller_test.rb

- Still using the "new" controller action, but rendering either "edit" with a form, or "show" with a success message.
- No longer scold the user for following the link twice or reloading the page.
- Awaiting feedback on the content of the three success messages, so leaving this in draft in hope of getting the nontechnical details squared
away on this ticket/PR.
- db/seeds.rb removes old `ht_web.otis_registrations` entries that can cause referential integrity issues with deleted `ht_institutions`.

DEV-212 Make registration more like unsubscribing from mailing list

---

test/models/ip_restriction_test.rb

- Add `require "ip_restriction"` to test file to prevent occasional uninitialized constant errors.

DEV-243 OTIS tests sporadically fail

---

app/controllers/finalize_controller.rb
app/controllers/ht_registrations_controller.rb
app/lib/otis/registration_mover.rb
app/mailers/registration_mailer.rb
app/models/expiration_date.rb
app/models/ht_registration.rb
app/models/ht_user.rb
app/presenters/ht_registration_presenter.rb
app/views/finalize/show.html.erb
app/views/ht_registrations/preview.html.erb
app/views/ht_registrations/show.html.erb
config/locales/en.yml
config/locales/ja.yml
db/schema.rb
db/seeds.rb
test/controllers/finalize_controller_test.rb
test/controllers/ht_registrations_controller_test.rb
test/factories.rb
test/mailers/previews/registration_mailer_preview.rb
test/mailers/registration_mailer_test.rb
test/presenters/ht_registration_presenter_test.rb
test/registration_mover_test.rb

- Rename `otis_registrations` fields starting with `dsp_` to `applicant_`.
- Add 30- and 180-day expiration periods introduced in CAA registration form.
- Add `hathitrust_authorizer` field for CAA users.
- Add `role` field with limited set of ATRS + CAA roles (and note that this smaller set will need to be reconciled with what's in `ht_users`).

DEV-50 Update registration form fields to match new registration form.

---

Gemfile.lock
config/environments/test.rb
config/locales/en.yml
config/locales/ja.yml

- Replace unused `en.ht_registration.values.role.atrs` with `en.ht_registration.values.role.ssd` and `en.ht_registration.values.role.ssdproxy`.
- Force missing translations to throw exceptions in test environment config (some errors just cannot be caught by I18n-tasks).
- Suppress pedantic "warning: parser/current is loading parser/ruby30..." noise by updating `parser` gem.

DEV-262 OTIS Registration I18n Warnings

---

app/presenters/ht_registration_presenter.rb
app/views/ht_registrations/show.html.erb
app/views/layouts/application.html.erb
config/locales/en.yml
config/locales/ja.yml
test/controllers/ht_registrations_controller_test.rb
test/test_helper.rb

- Move WHOIS query from registration show page view to presenter.
- Add WHOIS exception handling and localized error message.
- Add ability to force WHOIS testing stub to throw exception.
- Sneak current locale into `<html>` tag in app layout (to make HTML validators happy).

DEV-265 OTIS vs WHOIS

---

app/controllers/ht_registrations_controller.rb
app/lib/otis/registration_mover.rb
config/locales/en.yml
config/locales/ja.yml
test/controllers/ht_registrations_controller_test.rb

- Add `RegistrationMover.user_exists?` utility called by registrations controller.
- This seemed like the logical place to put it since that class concerns itself with both registrations and users.

DEV-286 OTIS should not allow new registrations for existing users

---

lib/tasks/daily_digest.rake
test/lib/tasks/daily_digest_test.rb
test/mailers/daily_digest_mailer_test.rb

- Rake task uses ENV['RAKE_DEFAULT_URL_HOST'] for default URL host in ActionMailer config.
- Some peculiar shenanigans required for testing.
- No changes to config for OTIS as a whole.

DEV-54 fix for OTIS daily digest

---

.github/workflows/deploy-production.yaml

- Adopt `v2` of `mlibrary/deploy-to-kubernetes`
- Deploy `daily-digest` cron job to production.
- Clean up vestigial `### DONE` annotations from previous round of development.

Add cronjob to Deploy to Production workflow.

---

app/lib/otis/registration_mover.rb
app/models/ht_user.rb
test/registration_mover_test.rb

- Create new user with MFA enabled if registration MFA Addendum is set.
- Check for existing registration with addendum when validating `ht_user.mfa`.
- Note that the latter depends on old registrations hanging around in order to license `ht_user.mfa` when it conflicts with our institution record.

DEV-314 OTIS does not do anything with MFA Addendum

---

app/assets/stylesheets/application.scss
config/environments/development.rb

- Add reference to flag-icons-rails in app SCSS to restore US flag to ht_institutions.us.
- Replace deprecated config.web_console.whitelisted_ips (unrelated but necessary to do eventually).

DEV-351 OTIS ht_institutions.us display broken

---

Gemfile.lock
app/controllers/ht_registrations_controller.rb
app/lib/otis/registration_mover.rb
app/models/ht_registration.rb
app/presenters/ht_registration_presenter.rb
app/views/ht_registrations/show.html.erb
config/locales/en.yml
config/locales/ja.yml
config/settings.yml
db/seeds.rb
docker-compose.yml
test/controllers/ht_registrations_controller_test.rb
test/factories.rb
test/registration_mover_test.rb

*As a CAA user, I want to re-gain access when my identity as provided by my IdP has changed so that I can continue to use the service.*
- Allow HTRegistration to be created even if it shares an e-mail with an existing user.
- Add localized "Existing User" badge to registration email field (on show page) as a warning that this is a re-registration.
- `RegistrationMover` updates existing users where appropriate instead of always creating anew.
- Condition availability of "Create User" (and new alternate "Update User") button on `finished` status of registration.
- Add a warning + no-op if the operator somehow manages to submit "Create/Update User" twice.
- QoL improvements for the devs
- Remove that *gottverdammt* pid file when running `web` service.
- Create some fake registrations with …

DEV-319 Register IDP Change

---

app/views/shared/_approval_request_body.html.erb
app/views/shared/_approval_request_user_email.html.erb
app/views/shared/_registration_body.html.erb
app/views/user_mailer/approval_request_user_email.text.erb
config/settings.yml
test/system/ht_registrations_test.rb

- Move support email to settings and interpolate into templates.
- Fix system test with Capybara ambiguous element error.

DEV-438 update otis to use support@hathitrust.org

---

bin/run_system_tests.sh
test/system/ht_approval_requests_test.rb

- Bail out of `bin/run_system_tests.sh` with nonzero exit status instead of running cleanup code.
- Fix approval request URL extraction in system tests when there are multiple URLs.

DEV-448 OTIS system tests fail silently

---

Gemfile
Gemfile.lock

Didn't manifest as dependencies in development, but production failed to start. These were formerly included as core gems but aren't in ruby 3.1.

Add net-imap and net-pop

---

.github/workflows/manual-deploy-staging.yml
Gemfile
Gemfile.lock

- Downgrade Sequel to version prior to Ruby 3.1 upgrade.
- Add manual release to staging action
- Incorporate fix to release to testing action (upon which the above is obviously based)

TTO-10 Sequel Downgrade

---

app/lib/otis/registration_mover.rb
test/registration_mover_test.rb

- `RegistrationMover` grants access "normal" to ssdproxy registrations and "total" otherwise.
- Would like confirmation from the reviewer that the business logic is sound.

TTO-66 ssdproxy users should have access=normal

---

app/lib/otis/institutions_export.rb
config/settings.yml
config/settings/production.yml
lib/tasks/institutions_export.rake
test/institutions_export_test.rb
test/lib/tasks/daily_digest_task_test.rb
test/lib/tasks/institutions_export_task_test.rb
test/test_helper.rb

- Add `InstitutionsExport` class and rake task that invokes it.
- Add three config values:
- `ht_institutions_file`
- `ht_saml_entity_ids_file`
- `export_files_directory`
- `ht_tanka` is setting `EXPORT_FILES_DIRECTORY` to `/htapps/www/files/tmp/` temporarily, for evaluation.
- Maintenance:
- Annoying name collision fixed: rename `test/lib/tasks/daily_digest_test.rb` to `daily_digest_task_test.rb`
- Call `Otis::Application.load_tasks` in test helper to keep rake tests from clobbering each other's coverage

DEV-1019 Move ht_institutions cron job to OTIS

---

app/lib/otis/institutions_export.rb
lib/tasks/institutions_export.rake
test/institutions_export_test.rb
test/lib/tasks/institutions_export_task_test.rb

- Neither export file should contain institutions with enabled=0
- SAML entities file should contain only enabled=1 institutions
- Add tests for correct number of entries in export files
- Add trailing newline to both export files

DEV-1019 Move ht_institutions cron job to OTIS (fixes)

---

Gemfile
Gemfile.lock
README.md
app/assets/javascripts/application.js
app/controllers/ht_institutions_controller.rb
app/controllers/ht_users_controller.rb
app/views/ht_institutions/index.html.erb
app/views/ht_users/index.html.erb
config/locales/en.yml
config/locales/ja.yml
docker-compose.yml
docker-compose.yml.arm64
test/controllers/ht_users_controller_test.rb

First Commit:
- Add `popper_js` gem to add support for Bootstrap dropdown menus.
- Move institutions CSV download button to top of page.
- Move users CSV download button to top of page and add option to exclude ATRS users.
- Add `role_filter` option to `ht_users` controller for CSV requests.
Second Commit:
- TIDY: replace obsolete `docker-compose` invocations (addresses issue #218)
Later Commits:
- Standardrb fixes.
- Fixes swapped labels/URLs on the Users CSV download dropdown menu.
- Override default download filenames.
**Reviewer:**
Background at https://hathitrust.atlassian.net/browse/DEV-1242
- Please follow the "Trying it out" README instructions and then login as `admin@default.invalid` at `http://localhost:3000/useradmin`
- Viewing user list (slow default page) is there a …

DEV-1242 Add report export functionality to OTIS

---

Gemfile.lock
app/views/ht_approval_requests/edit.html.erb
app/views/ht_registrations/preview.html.erb
config/initializers/ckeditor.rb

- Update to latest open-source version of CKEditor 4 and latest gem.
- Set `CKEDITOR.config.versionCheck = false;` to suppress chatty warnings.
- Note: CKEditor 4 has been EOL for a year, see https://github.com/hathitrust/otis/issues/225

TTO-246 Alert to Update CKE Editor in OTIS

---

Gemfile
Gemfile.lock
README.md
app/controllers/ht_ssd_proxy_reports_controller.rb
app/helpers/application_helper.rb
app/models/ht_hathifile.rb
app/models/ht_institution.rb
app/models/ht_ssd_proxy_report.rb
app/presenters/ht_ssd_proxy_report_presenter.rb
app/views/ht_ssd_proxy_reports/index.html.erb
app/views/layouts/application.html.erb
config/initializers/inflections.rb
config/locales/en.yml
config/locales/ja.yml
config/routes.rb
db/ht_web.sql
db/schema.rb
db/seeds.rb
lib/tasks/clear_database.rake
test/controllers/ht_ssd_proxy_reports_controller_test.rb
test/factories.rb
test/models/ht_hathifile_test.rb
test/models/ht_institution_test.rb
test/models/ht_ssd_proxy_report_test.rb
test/presenters/ht_ssd_proxy_report_presenter_test.rb
test/system/ht_ssd_proxy_reports_test.rb

This PR adds a new page to Otis: SSD Proxy Reports, based on a facility hidden away in PageTurner. The existing facility uses some of the advanced features of Bootstrap Tables that have been replicated here, and (one hopes) improved upon. Otis uses Bootstrap Tables but until now has not taken advantage of advanced search features, pagination, data export, or a server-side provider (via `format=json`).
Most of the changes in this PR are boilerplate - two new database tables, seeds and factories for them, localizations.
- Proceed with this branch locally as described in the README by building and running the `web` service.
- Please evaluate the basic functionality at `http://0.0.0.0:3000/useradmin/ht_ssd_proxy_reports`, logging in as `admin@default.invalid`. The behavior should at least …

DEV-1241 SSD Proxy Reports from PT

---

app/controllers/ht_users_controller.rb
app/models/ht_approval_request.rb
app/models/ht_user.rb
app/presenters/ht_user_presenter.rb

- `@all_users` was being populated via SQL in all cases even though it was only used for CSV download.
- The query has been removed and the CSV now uses the active + inactive arrays so the query was redundant anyway.
- The controller now uses `includes` instead of `joins` to pick up the institution and approval request data for each user.
- Presenter can just call `ht_approval_request.first` since the controller's query applies the `ORDER BY` we want. This eliminates one additional query per user.

Remove unnecessary query to try to speed up ht_users index page.

---

package-lock.json
package.json

- Manually install official version of xlsx/SheetJS instead of stale (and vulnerable) one on npm registry.
- Pin sass to 1.77.6 to silence deluge of warnings.

DEV-1600 address outdated bootstrap table export component 

---

app/controllers/ht_approval_requests_controller.rb
app/controllers/ht_users_controller.rb
app/models/ht_user.rb
test/controllers/ht_users_controller_test.rb

`HTUser#add_or_update_renewal` was designed to update/create/check the audit trail when a user's expiration date is updated. This can happen via outside approval or manually inside Otis (User->Edit->change date). However, it renewed the user (bumped the expiration date) as a side effect. This behavior is correct when an approval request for a supervisor outside HathiTrust is processed. It is not correct when a manual update is done, because the expiration date gets updated twice: once from the HTML form and a second time by this method.
This patch:
- Adds comments about what `HTUser#add_or_update_renewal` does.
- Moves responsibility for calling `HTUser#renew!` to the caller, specifically `HTApprovalRequestsController`.
- Adds one initially failing test that validates expiration date when …

DEV-1609 manually renewing user causes double renewal

---

app/controllers/ht_approval_requests_controller.rb
app/controllers/ht_registrations_controller.rb
app/mailers/approval_request_mailer.rb
app/mailers/registration_mailer.rb
app/views/approval_request_mailer/approval_request_email.html.erb
app/views/approval_request_mailer/approval_request_email.text.erb
app/views/ht_approval_requests/edit.html.erb
app/views/ht_registrations/preview.html.erb
app/views/registration_mailer/registration_email.html.erb
app/views/registration_mailer/registration_email.text.erb
test/controllers/ht_approval_requests_controller_test.rb
test/controllers/ht_registrations_controller_test.rb
test/mailers/approval_request_mailer_test.rb
test/mailers/previews/approval_request_mailer_preview.rb
test/mailers/previews/registration_mailer_preview.rb
test/mailers/registration_mailer_test.rb

In the migration from `ckeditor` 4 to 5 the `textarea` that contains the email body (for approval request and registration emails) lost its `name` attribute, so we sent out some emails that omitted most of the intended content.
- Restore `email_body` form element name to approval request and registration email previews.
- The changes in this PR that actually fix the bug are in `preview.html.erb` and `edit.html.erb`, everything else is just tests & tidy.
- Mailers now raise if the `email_body` is omitted. Better a 500 than a mostly blank e-mail being sent. This required some modifications to the tests, to make sure we have some fake body text.
- TIDY phase: at the Controller-Mailer interface the `email_body` param was getting renamed to just `body` as a Mailer instance variable. For naming …

TTO-301 Otis: investigate possible missing e-mail registration text
